// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/convert/daily": {
            "post": {
                "description": "Accepts raw user daily emissions in kg CO2 and translates them into financial costs (USD and local currency) using country carbon tax pricing data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversion"
                ],
                "summary": "Convert daily carbon emissions to currency valuation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "3-letter country code (e.g., IDN, ARG)",
                        "name": "country_code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Daily emission data",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/convert-emission-service_internal_domain.UserDailyEmission"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/convert-emission-service_internal_domain.UserDailyCostResponse"
                        }
                    },
                    "400": {
                        "description": "Example: {'error': 'invalid country_code query param format'}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Example: {'error': 'internal database failure'}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/convert/monthly": {
            "post": {
                "description": "Accepts monthly aggregate emissions and breakdown lists, returning mapped cost breakdowns per day alongside totals.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversion"
                ],
                "summary": "Convert monthly carbon emissions to currency valuation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "3-letter country code (e.g., IDN, ARG)",
                        "name": "country_code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Monthly emission dataset",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/convert-emission-service_internal_domain.UserMonthlyEmission"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/convert-emission-service_internal_domain.UserMonthlyCostResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/convert/yearly": {
            "post": {
                "description": "Accepts structural yearly datasets and returns complex valuation arrays grouped by calendar month.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversion"
                ],
                "summary": "Convert yearly carbon emissions to currency valuation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "3-letter country code (e.g., IDN, ARG)",
                        "name": "country_code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Yearly emission dataset",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/convert-emission-service_internal_domain.UserYearlyEmission"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/convert-emission-service_internal_domain.UserYearlyCostResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "convert-emission-service_internal_domain.CarbonCostValuation": {
            "type": "object",
            "properties": {
                "total_cost_local_cur": {
                    "type": "number"
                },
                "total_cost_usd": {
                    "type": "number"
                },
                "total_emission_kg_co2": {
                    "type": "number"
                }
            }
        },
        "convert-emission-service_internal_domain.UserDailyCostResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "valuation": {
                    "$ref": "#/definitions/convert-emission-service_internal_domain.CarbonCostValuation"
                }
            }
        },
        "convert-emission-service_internal_domain.UserDailyEmission": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "total_emission_kg_co2": {
                    "type": "number"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "convert-emission-service_internal_domain.UserMonthlyCostResponse": {
            "type": "object",
            "properties": {
                "daily_cost_detail": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/convert-emission-service_internal_domain.UserDailyCostResponse"
                    }
                },
                "total_valuation": {
                    "$ref": "#/definitions/convert-emission-service_internal_domain.CarbonCostValuation"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "convert-emission-service_internal_domain.UserMonthlyEmission": {
            "type": "object",
            "properties": {
                "daily_emissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/convert-emission-service_internal_domain.UserDailyEmission"
                    }
                },
                "total_emission_monthly_kg_co2": {
                    "type": "number"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "convert-emission-service_internal_domain.UserMonthlyEmissionDetail": {
            "type": "object",
            "properties": {
                "month": {
                    "type": "string"
                },
                "total_emission_kg_co2": {
                    "type": "number"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "convert-emission-service_internal_domain.UserYearlyCostResponse": {
            "type": "object",
            "properties": {
                "monthly_cost_detail": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/convert-emission-service_internal_domain.UserMonthlyCostResponse"
                    }
                },
                "total_valuation": {
                    "$ref": "#/definitions/convert-emission-service_internal_domain.CarbonCostValuation"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "convert-emission-service_internal_domain.UserYearlyEmission": {
            "type": "object",
            "properties": {
                "monthly_emissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/convert-emission-service_internal_domain.UserMonthlyEmissionDetail"
                    }
                },
                "total_emission_yearly_kg_co2": {
                    "type": "number"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Convert Emission API",
	Description:      "This is a microservice responsible for converting carbon emission into local currency.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
