version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - auth-service
      - count-emission-service
      - notification-service
      - convert-emission-service
    networks:
      - climate-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "8081:8081"
    env_file: .env
    networks:
      - climate-network

  count-emission-service:
    build:
      context: ./count-emission-service
      dockerfile: Dockerfile
    container_name: count_emission_service
    ports:
      - "50051:50051"
    env_file: .env
    networks:
      - climate-network

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification_service
    ports:
      - "50052:50052"
    env_file: .env
    depends_on:
      - count-emission-service
    networks:
      - climate-network

  convert-emission-service:
    build:
      context: ./convert-emission-service
      dockerfile: Dockerfile
    container_name: convert_emission_service
    ports:
      - "50053:50053"
    env_file: .env
    networks:
      - climate-network

networks:
  climate-network:
    driver: bridge
