// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: emission.proto

// Client-side contract matching count-emission-service.
// Only the RPCs notification-service needs are declared here.

package emission

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Emission_GetDailyTotal_FullMethodName      = "/generated.Emission/GetDailyTotal"
	Emission_GetUserPreferences_FullMethodName = "/generated.Emission/GetUserPreferences"
)

// EmissionClient is the client API for Emission service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmissionClient interface {
	GetDailyTotal(ctx context.Context, in *DailyTotalRequest, opts ...grpc.CallOption) (*DailyTotalResponse, error)
	GetUserPreferences(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UserPreferences, error)
}

type emissionClient struct {
	cc grpc.ClientConnInterface
}

func NewEmissionClient(cc grpc.ClientConnInterface) EmissionClient {
	return &emissionClient{cc}
}

func (c *emissionClient) GetDailyTotal(ctx context.Context, in *DailyTotalRequest, opts ...grpc.CallOption) (*DailyTotalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DailyTotalResponse)
	err := c.cc.Invoke(ctx, Emission_GetDailyTotal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emissionClient) GetUserPreferences(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UserPreferences, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserPreferences)
	err := c.cc.Invoke(ctx, Emission_GetUserPreferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmissionServer is the server API for Emission service.
// All implementations must embed UnimplementedEmissionServer
// for forward compatibility.
type EmissionServer interface {
	GetDailyTotal(context.Context, *DailyTotalRequest) (*DailyTotalResponse, error)
	GetUserPreferences(context.Context, *Empty) (*UserPreferences, error)
	mustEmbedUnimplementedEmissionServer()
}

// UnimplementedEmissionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmissionServer struct{}

func (UnimplementedEmissionServer) GetDailyTotal(context.Context, *DailyTotalRequest) (*DailyTotalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDailyTotal not implemented")
}
func (UnimplementedEmissionServer) GetUserPreferences(context.Context, *Empty) (*UserPreferences, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserPreferences not implemented")
}
func (UnimplementedEmissionServer) mustEmbedUnimplementedEmissionServer() {}
func (UnimplementedEmissionServer) testEmbeddedByValue()                  {}

// UnsafeEmissionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmissionServer will
// result in compilation errors.
type UnsafeEmissionServer interface {
	mustEmbedUnimplementedEmissionServer()
}

func RegisterEmissionServer(s grpc.ServiceRegistrar, srv EmissionServer) {
	// If the following call panics, it indicates UnimplementedEmissionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Emission_ServiceDesc, srv)
}

func _Emission_GetDailyTotal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DailyTotalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmissionServer).GetDailyTotal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Emission_GetDailyTotal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmissionServer).GetDailyTotal(ctx, req.(*DailyTotalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Emission_GetUserPreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmissionServer).GetUserPreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Emission_GetUserPreferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmissionServer).GetUserPreferences(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Emission_ServiceDesc is the grpc.ServiceDesc for Emission service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Emission_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "generated.Emission",
	HandlerType: (*EmissionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDailyTotal",
			Handler:    _Emission_GetDailyTotal_Handler,
		},
		{
			MethodName: "GetUserPreferences",
			Handler:    _Emission_GetUserPreferences_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emission.proto",
}
