// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: emission.proto

// Client-side contract matching count-emission-service.
// Only the RPCs notification-service needs are declared here.

package emission

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_emission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_emission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_emission_proto_rawDescGZIP(), []int{0}
}

type DailyTotalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyTotalRequest) Reset() {
	*x = DailyTotalRequest{}
	mi := &file_emission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyTotalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyTotalRequest) ProtoMessage() {}

func (x *DailyTotalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyTotalRequest.ProtoReflect.Descriptor instead.
func (*DailyTotalRequest) Descriptor() ([]byte, []int) {
	return file_emission_proto_rawDescGZIP(), []int{1}
}

func (x *DailyTotalRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DailyTotalRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type DailyTotalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DailyTotalKg  float32                `protobuf:"fixed32,1,opt,name=daily_total_kg,json=dailyTotalKg,proto3" json:"daily_total_kg,omitempty"`
	TripCount     int32                  `protobuf:"varint,2,opt,name=trip_count,json=tripCount,proto3" json:"trip_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyTotalResponse) Reset() {
	*x = DailyTotalResponse{}
	mi := &file_emission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyTotalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyTotalResponse) ProtoMessage() {}

func (x *DailyTotalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyTotalResponse.ProtoReflect.Descriptor instead.
func (*DailyTotalResponse) Descriptor() ([]byte, []int) {
	return file_emission_proto_rawDescGZIP(), []int{2}
}

func (x *DailyTotalResponse) GetDailyTotalKg() float32 {
	if x != nil {
		return x.DailyTotalKg
	}
	return 0
}

func (x *DailyTotalResponse) GetTripCount() int32 {
	if x != nil {
		return x.TripCount
	}
	return 0
}

type UserPreferences struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UserId                int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CountryCode           string                 `protobuf:"bytes,2,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	CustomDailyLimitKgCo2 float64                `protobuf:"fixed64,3,opt,name=custom_daily_limit_kg_co2,json=customDailyLimitKgCo2,proto3" json:"custom_daily_limit_kg_co2,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UserPreferences) Reset() {
	*x = UserPreferences{}
	mi := &file_emission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreferences) ProtoMessage() {}

func (x *UserPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_emission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPreferences.ProtoReflect.Descriptor instead.
func (*UserPreferences) Descriptor() ([]byte, []int) {
	return file_emission_proto_rawDescGZIP(), []int{3}
}

func (x *UserPreferences) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserPreferences) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *UserPreferences) GetCustomDailyLimitKgCo2() float64 {
	if x != nil {
		return x.CustomDailyLimitKgCo2
	}
	return 0
}

var File_emission_proto protoreflect.FileDescriptor

const file_emission_proto_rawDesc = "" +
	"\n" +
	"\x0eemission.proto\x12\tgenerated\"\a\n" +
	"\x05Empty\"@\n" +
	"\x11DailyTotalRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\"Y\n" +
	"\x12DailyTotalResponse\x12$\n" +
	"\x0edaily_total_kg\x18\x01 \x01(\x02R\fdailyTotalKg\x12\x1d\n" +
	"\n" +
	"trip_count\x18\x02 \x01(\x05R\ttripCount\"\x87\x01\n" +
	"\x0fUserPreferences\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12!\n" +
	"\fcountry_code\x18\x02 \x01(\tR\vcountryCode\x128\n" +
	"\x19custom_daily_limit_kg_co2\x18\x03 \x01(\x01R\x15customDailyLimitKgCo22\x9c\x01\n" +
	"\bEmission\x12L\n" +
	"\rGetDailyTotal\x12\x1c.generated.DailyTotalRequest\x1a\x1d.generated.DailyTotalResponse\x12B\n" +
	"\x12GetUserPreferences\x12\x10.generated.Empty\x1a\x1a.generated.UserPreferencesB%Z#notification-service/proto/emissionb\x06proto3"

var (
	file_emission_proto_rawDescOnce sync.Once
	file_emission_proto_rawDescData []byte
)

func file_emission_proto_rawDescGZIP() []byte {
	file_emission_proto_rawDescOnce.Do(func() {
		file_emission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_emission_proto_rawDesc), len(file_emission_proto_rawDesc)))
	})
	return file_emission_proto_rawDescData
}

var file_emission_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_emission_proto_goTypes = []any{
	(*Empty)(nil),              // 0: generated.Empty
	(*DailyTotalRequest)(nil),  // 1: generated.DailyTotalRequest
	(*DailyTotalResponse)(nil), // 2: generated.DailyTotalResponse
	(*UserPreferences)(nil),    // 3: generated.UserPreferences
}
var file_emission_proto_depIdxs = []int32{
	1, // 0: generated.Emission.GetDailyTotal:input_type -> generated.DailyTotalRequest
	0, // 1: generated.Emission.GetUserPreferences:input_type -> generated.Empty
	2, // 2: generated.Emission.GetDailyTotal:output_type -> generated.DailyTotalResponse
	3, // 3: generated.Emission.GetUserPreferences:output_type -> generated.UserPreferences
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_emission_proto_init() }
func file_emission_proto_init() {
	if File_emission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_emission_proto_rawDesc), len(file_emission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_emission_proto_goTypes,
		DependencyIndexes: file_emission_proto_depIdxs,
		MessageInfos:      file_emission_proto_msgTypes,
	}.Build()
	File_emission_proto = out.File
	file_emission_proto_goTypes = nil
	file_emission_proto_depIdxs = nil
}
