// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dailytotal.proto

package dailytotal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DailyTotalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyTotalRequest) Reset() {
	*x = DailyTotalRequest{}
	mi := &file_dailytotal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyTotalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyTotalRequest) ProtoMessage() {}

func (x *DailyTotalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dailytotal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*DailyTotalRequest) Descriptor() ([]byte, []int) {
	return file_dailytotal_proto_rawDescGZIP(), []int{0}
}

func (x *DailyTotalRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DailyTotalRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type DailyTotalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DailyTotalKg  float32                `protobuf:"fixed32,1,opt,name=daily_total_kg,json=dailyTotalKg,proto3" json:"daily_total_kg,omitempty"`
	TripCount     int32                  `protobuf:"varint,2,opt,name=trip_count,json=tripCount,proto3" json:"trip_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyTotalResponse) Reset() {
	*x = DailyTotalResponse{}
	mi := &file_dailytotal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyTotalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyTotalResponse) ProtoMessage() {}

func (x *DailyTotalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dailytotal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*DailyTotalResponse) Descriptor() ([]byte, []int) {
	return file_dailytotal_proto_rawDescGZIP(), []int{1}
}

func (x *DailyTotalResponse) GetDailyTotalKg() float32 {
	if x != nil {
		return x.DailyTotalKg
	}
	return 0
}

func (x *DailyTotalResponse) GetTripCount() int32 {
	if x != nil {
		return x.TripCount
	}
	return 0
}

var File_dailytotal_proto protoreflect.FileDescriptor

// Binary descriptor for:
//
//	syntax = "proto3";
//	package pb;
//	option go_package = "count-emission-service/proto/dailytotal";
//	message DailyTotalRequest  { int32 user_id = 1; string date = 2; }
//	message DailyTotalResponse { float daily_total_kg = 1; int32 trip_count = 2; }
const file_dailytotal_proto_rawDesc = "" +
	"\x0a\x10dailytotal.proto" +
	"\x12\x02pb" +
	"\x22\x40\x0a\x11DailyTotalRequest" +
	"\x12\x17\x0a\x07user_id\x18\x01\x20\x01\x28\x05\x52\x06userId" +
	"\x12\x12\x0a\x04date\x18\x02\x20\x01\x28\x09\x52\x04date" +
	"\x22\x59\x0a\x12DailyTotalResponse" +
	"\x12\x24\x0a\x0edaily_total_kg\x18\x01\x20\x01\x28\x02\x52\x0cdailyTotalKg" +
	"\x12\x1d\x0a\x0atrip_count\x18\x02\x20\x01\x28\x05\x52\x09tripCount" +
	"\x42\x29\x5a\x27count-emission-service/proto/dailytotal" +
	"\x62\x06proto3"

var (
	file_dailytotal_proto_rawDescOnce sync.Once
	file_dailytotal_proto_rawDescData []byte
)

func file_dailytotal_proto_rawDescGZIP() []byte {
	file_dailytotal_proto_rawDescOnce.Do(func() {
		file_dailytotal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dailytotal_proto_rawDesc), len(file_dailytotal_proto_rawDesc)))
	})
	return file_dailytotal_proto_rawDescData
}

var file_dailytotal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dailytotal_proto_goTypes = []any{
	(*DailyTotalRequest)(nil),  // 0: pb.DailyTotalRequest
	(*DailyTotalResponse)(nil), // 1: pb.DailyTotalResponse
}
var file_dailytotal_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dailytotal_proto_init() }

func file_dailytotal_proto_init() {
	if File_dailytotal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dailytotal_proto_rawDesc), len(file_dailytotal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dailytotal_proto_goTypes,
		DependencyIndexes: file_dailytotal_proto_depIdxs,
		MessageInfos:      file_dailytotal_proto_msgTypes,
	}.Build()
	File_dailytotal_proto = out.File
	file_dailytotal_proto_goTypes = nil
	file_dailytotal_proto_depIdxs = nil
}
