// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/convert.proto

package convert

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Convert_ConvertToIDR_FullMethodName = "/pb.Convert/ConvertToIDR"
)

// ConvertClient is the client API for Convert service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConvertClient interface {
	ConvertToIDR(ctx context.Context, in *ConvertToIDRRequest, opts ...grpc.CallOption) (*ConvertToIDRResponse, error)
}

type convertClient struct {
	cc grpc.ClientConnInterface
}

func NewConvertClient(cc grpc.ClientConnInterface) ConvertClient {
	return &convertClient{cc}
}

func (c *convertClient) ConvertToIDR(ctx context.Context, in *ConvertToIDRRequest, opts ...grpc.CallOption) (*ConvertToIDRResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvertToIDRResponse)
	err := c.cc.Invoke(ctx, Convert_ConvertToIDR_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConvertServer is the server API for Convert service.
// All implementations must embed UnimplementedConvertServer
// for forward compatibility.
type ConvertServer interface {
	ConvertToIDR(context.Context, *ConvertToIDRRequest) (*ConvertToIDRResponse, error)
	mustEmbedUnimplementedConvertServer()
}

// UnimplementedConvertServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConvertServer struct{}

func (UnimplementedConvertServer) ConvertToIDR(context.Context, *ConvertToIDRRequest) (*ConvertToIDRResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConvertToIDR not implemented")
}
func (UnimplementedConvertServer) mustEmbedUnimplementedConvertServer() {}
func (UnimplementedConvertServer) testEmbeddedByValue()                 {}

// UnsafeConvertServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConvertServer will
// result in compilation errors.
type UnsafeConvertServer interface {
	mustEmbedUnimplementedConvertServer()
}

func RegisterConvertServer(s grpc.ServiceRegistrar, srv ConvertServer) {
	// If the following call panics, it indicates UnimplementedConvertServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Convert_ServiceDesc, srv)
}

func _Convert_ConvertToIDR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertToIDRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConvertServer).ConvertToIDR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Convert_ConvertToIDR_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConvertServer).ConvertToIDR(ctx, req.(*ConvertToIDRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Convert_ServiceDesc is the grpc.ServiceDesc for Convert service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Convert_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Convert",
	HandlerType: (*ConvertServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConvertToIDR",
			Handler:    _Convert_ConvertToIDR_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/convert.proto",
}
